#!/bin/bash -x
present=1
randomCheck=$((RANDOM%2))
if [ $randomCheck -eq 1 ]
then
     echo "The Employee is Present"
     empRateHrs=20
     empHrs=8     
     salary=$(($empRateHrs*$empHrs))
else
     echo "The employee is Absent"
     salary=0
fi
