#!/bin/bash -x
fullTime=2
partTime=1
maxHrsInMonth=10
empRatePerHr=20
workingDays=20
empWorkingDays=0
totalEmpHrs=0
randomCheck=$((RANDOM%3))
while [[ $totalEmpHrs -lt $maxHrsInMonth && $empWorkingDays -lt $empWorkingDays ]]
do
  ((empWorkingDays++))
    case $randomcheck in
          $fullTime)    empHrs=8
                          ;;
          $partTime)    empHrs=4
                          ;;
            *)          empHrs=0
                          ;;
    esac
  totalEmpHrs=$(($totalEmpHrs+$empHrs))
done
salary=$(($totalEmpHrs*empRatePerHr))
