#!/bin/bash -x
fullTime=2
partTime=1
maxHrsInMonth=4
empRatePerHr=20
workingDays=20
empWorkingDays=0
totalEmpHrs=0
function working_Hrs_Days()
{
    case $randomcheck in
          $fullTime)    empHrs=8
                          ;;
          $partTime)    empHrs=4
                          ;;
            *)          empHrs=0
                          ;;
    esac
    echo $empHrs
}
   while [[ $totalEmpHrs -lt $maxHrsInMonth && $empWorkingDays -lt $WorkingDays ]]
   do
        ((empWorkingDays++))
        empHrs=$( working_hrs_Days $((RANDOM%3)) )   
        totalEmpHrs=$(($totalEmpHrs+$empHrs))
   done
salary=$(($totalEmpHrs*empRatePerHr))

