#!/bin/bash -x
fullTime=1
partTime=2
empRateHrs=20
randomCheck=$((RANDOM%3))
if [ $fullTime -eq $randomCheck ]
then
     echo "The Employee is full time Present"
     workingDays=20
     salary=$(($empRateHrs*$workingDays))
elif [ $partTime -eq $randomCheck ]
then
     echo "The employee is part time present"
     workingDays=10
     salary=$(($empRateHrs*$workingDays))
else
     echo "Employee is Absent"
     salary=0
fi
